# action.yml
name: 'Huawei Cloud OBS Upload'
description: 'Huawei Cloud OBS Upload'
inputs:
  access_key:
    description: "Access key id"
    required: true
  secret_key:
    description: "Secret access key"
    required: true
  region:
    description: 'Region'
    required: false
    default: 'cn-north-4'
  bucket_name:
    description: "The name of the bucket you want to upload"
    required: true
  obsutil_url:
    description:
    required: true
    default: 'https://obs-community.obs.cn-north-1.myhuaweicloud.com/obsutil/current/obsutil_linux_amd64.tar.gz'
  file_path:
    description: "The name of the file or directory you want to upload"
    required: true  
runs:
  using: 'docker'
  image: 'Dockerfile'
